---
- name: Deploy monitoring stack
  hosts: monitor
  become: true
  vars:
    docker_users: [ubuntu]
  roles:
    - geerlingguy.docker
  tasks:
    - name: Create folder stack
      file:
        path: /opt/monitoring
        state: directory

    - name: Deploy prometheus.yaml
      copy:
        src: prometheus.yaml
        dest: /opt/monitoring/prometheus.yaml
        register: prometheus_config

    - name: Deploy compose.yaml
      copy:
        src: compose.yaml
        dest: /opt/monitoring/compose.yaml
        register: compose_config

    - name: Launch container
      command: docker compose up -d
      args:
        chdir: /opt/monitoring
      when: prometheus_config.changed or compose_config.changed
      register: compose_up
