---
- name: Install Docker on all nodes
  hosts: nodes
  become: true

  tasks:
    - name: Download Docker install script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'

    - name: Run Docker install script
      command: sh /tmp/get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: true

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Python Docker SDK
      apt:
        name: python3-docker
        state: present
  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
